Repository tangent-opensource/hdBlackbird, pull requests merged in 2021-04, with the labels that each got.

#130 Hair texture coordinates
  plugin/hdCycles/basisCurves.cpp
Labels: enhancement

#141 Use tbb to set number of threads
  plugin/hdCycles/config.cpp
  plugin/hdCycles/config.h
  plugin/hdCycles/renderParam.cpp
Labels: bug

#149 Replace add/remove curve mesh with add/remove geometry
  plugin/hdCycles/basisCurves.cpp
  plugin/hdCycles/mesh.cpp
  plugin/hdCycles/points.cpp
  plugin/hdCycles/renderParam.cpp
  plugin/hdCycles/renderParam.h
  plugin/hdCycles/volume.cpp
Labels: enhancement

#150 Use cycles locking and removing lock/unlock mechanism
  plugin/hdCycles/basisCurves.cpp
  plugin/hdCycles/light.cpp
  plugin/hdCycles/material.cpp
  plugin/hdCycles/mesh.cpp
  plugin/hdCycles/points.cpp
  plugin/hdCycles/renderParam.cpp
  plugin/hdCycles/renderParam.h
  plugin/hdCycles/volume.cpp
Labels: bug, enhancement

#152 Distribution enum value out of range and fallback to default GGX
  plugin/hdCycles/material.cpp
Labels: bug

#154 fixing null ptr camera
  plugin/hdCycles/CMakeLists.txt
  plugin/hdCycles/objectSource.cpp
  plugin/hdCycles/objectSource.h
  plugin/hdCycles/renderDelegate.cpp
  plugin/hdCycles/renderDelegate.h
  plugin/hdCycles/renderPass.cpp
  plugin/hdCycles/renderPassState.cpp
  plugin/hdCycles/renderPassState.h
  plugin/hdCycles/resourceRegistry.cpp
Labels: bug

#157 Add new Diagnostic Delegate to re-direct errors to stdout
  plugin/hdCycles/renderDelegate.cpp
  plugin/hdCycles/renderDelegate.h
Labels: enhancement, technical debt

#158 Changed the tile_size render setting schema type to integer
  plugin/hdCycles/renderParam.cpp
  plugin/hdCycles/utils.cpp
  plugin/hdCycles/utils.h
  plugin/usdCycles/schema.usda
Labels: bug

#159 object source memory leak
  plugin/hdCycles/objectSource.cpp
Labels: bug

#160 fixing dead lock on point instances
  plugin/hdCycles/mesh.cpp
Labels: bug, technical debt
