Repository tangent-opensource/hdBlackbird, pull requests merged in 2021-05, with the labels that each got.

#164 Remove annoying clang format options
  .clang-format
  plugin/hdCycles/attributeSource.cpp
  plugin/hdCycles/basisCurves.cpp
  plugin/hdCycles/basisCurves.h
  plugin/hdCycles/camera.cpp
  plugin/hdCycles/config.cpp
  plugin/hdCycles/config.h
  plugin/hdCycles/hdcycles.h
  plugin/hdCycles/instancer.cpp
  plugin/hdCycles/light.cpp
  plugin/hdCycles/light.h
  plugin/hdCycles/material.cpp
  plugin/hdCycles/material.h
  plugin/hdCycles/mesh.cpp
  plugin/hdCycles/meshRefiner.cpp
  plugin/hdCycles/meshRefiner.h
  plugin/hdCycles/objectSource.cpp
  plugin/hdCycles/points.cpp
  plugin/hdCycles/renderBuffer.cpp
  plugin/hdCycles/renderDelegate.cpp
  plugin/hdCycles/renderParam.cpp
  plugin/hdCycles/renderPass.cpp
  plugin/hdCycles/renderPass.h
  plugin/hdCycles/renderPassState.cpp
  plugin/hdCycles/resourceRegistry.h
  plugin/hdCycles/utils.cpp
  plugin/hdCycles/volume.cpp
  plugin/usdCycles/moduleDeps.cpp
Labels: enhancement

#163 Domelight transform fixes
  plugin/hdCycles/light.cpp
Labels: bug

#165 Enables the ability to toggle between path/branched_path integrators for the viewport
  plugin/hdCycles/renderParam.cpp
Labels: bug

#168 Disconnecting preview shader outputs when they override Cycles'
  plugin/hdCycles/material.cpp
  plugin/hdCycles/material.h
Labels: bug

#148 Transformation motion blur
  CMakeLists.txt
  plugin/hdCycles/CMakeLists.txt
  plugin/hdCycles/basisCurves.cpp
  plugin/hdCycles/camera.cpp
  plugin/hdCycles/config.cpp
  plugin/hdCycles/config.h
  plugin/hdCycles/mesh.cpp
  plugin/hdCycles/mesh.h
  plugin/hdCycles/objectSource.cpp
  plugin/hdCycles/objectSource.h
  plugin/hdCycles/points.cpp
  plugin/hdCycles/renderDelegate.cpp
  plugin/hdCycles/renderDelegate.h
  plugin/hdCycles/renderParam.cpp
  plugin/hdCycles/resourceRegistry.cpp
  plugin/hdCycles/resourceRegistry.h
  plugin/hdCycles/transformSource.cpp
  plugin/hdCycles/transformSource.h
  plugin/hdCycles/volume.cpp
  plugin/ndrCycles/CMakeLists.txt
  plugin/usdCycles/CMakeLists.txt
  plugin/usdCycles/schema.usda
  tests/CMakeLists.txt
  tests/test_attributeSource.cpp
  tests/test_transformSource.cpp
  tests/tests.cpp
Labels: bug, enhancement, technical debt

#171 Thread safe add and remove where lock has not been acquired in the scope
  plugin/hdCycles/points.cpp
Labels: bug

#176 Do not commit private attributes that start with double underscore
  plugin/hdCycles/attributeSource.h
  plugin/hdCycles/basisCurves.cpp
  plugin/hdCycles/mesh.cpp
  plugin/hdCycles/objectSource.cpp
  plugin/hdCycles/objectSource.h
  plugin/hdCycles/points.cpp
  plugin/hdCycles/transformSource.h
Labels: enhancement

#177 fix point clouds get primvar
  plugin/hdCycles/points.cpp
Labels: bug

#178 Adding materials to Point Cloud
  plugin/hdCycles/points.cpp
  plugin/hdCycles/points.h
Labels: bug

#181 Update package.py
  package.py
Labels: rez release

#185 Do not commit cycles primvars as attribute source
  plugin/hdCycles/mesh.cpp
Labels: bug

#184 add higher debug level to expand macros
  plugin/hdCycles/CMakeLists.txt
Labels: enhancement

#187 change default radius for points
  plugin/hdCycles/points.cpp
Labels: enhancement

#188 Update package.py
  package.py
Labels: rez release

#183 Revisit schema and primvars for curves
  plugin/hdCycles/basisCurves.cpp
Labels: bug

#172 Added safety check for missing UDIM paths.
  plugin/hdCycles/utils.cpp
Labels: bug

#189 handle invalid meshes
  plugin/hdCycles/mesh.cpp
Labels: bug

#190 Update package.py
  package.py
Labels: rez release

#192 Adding support for UsdSkel
  CMakeLists.txt
  cmake/FindPixarUsd.cmake
  plugin/hdCycles/material.cpp
  plugin/hdCycles/renderDelegate.cpp
Labels: enhancement

#194 Cmake usd schema gen search path
  CMakeLists.txt
  cmake/FindHoudiniUsd.cmake
  cmake/FindPixarUsd.cmake
  cmake/FindUsd.cmake
Labels: enhancement

#195 update for subdivision surfaces
  plugin/hdCycles/mesh.cpp
  plugin/usdCycles/schema.usda
Labels: bug

#162 Display AOVs rework
  plugin/hdCycles/material.cpp
  plugin/hdCycles/renderBuffer.cpp
  plugin/hdCycles/renderBuffer.h
  plugin/hdCycles/renderDelegate.h
  plugin/hdCycles/renderParam.cpp
  plugin/hdCycles/renderParam.h
  plugin/hdCycles/renderPass.cpp
Labels: enhancement

#197 override refineLevel by schema
  plugin/hdCycles/mesh.cpp
Labels: bug

#191 Feature/texture cache
  plugin/hdCycles/config.cpp
  plugin/hdCycles/config.h
  plugin/hdCycles/renderParam.cpp
  plugin/usdCycles/schema.usda
Labels: enhancement

#198 update object during creation
  plugin/hdCycles/basisCurves.cpp
  plugin/hdCycles/mesh.cpp
Labels: bug

#200 instanced objects now respect their source transform.
  plugin/hdCycles/mesh.cpp
Labels: bug

#207 Handling crop render settings (dataWindowNDC)
  plugin/hdCycles/renderBuffer.cpp
  plugin/hdCycles/renderBuffer.h
  plugin/hdCycles/renderParam.cpp
  plugin/hdCycles/renderParam.h
Labels: enhancement

#208 Fix possible error when printing a string and warnings
  plugin/hdCycles/basisCurves.cpp
  plugin/hdCycles/mesh.cpp
  plugin/hdCycles/points.cpp
Labels: bug
