Repository tangent-opensource/hdBlackbird, pull requests merged in 2021-03, with the labels that each got.

#78 Added displacement node to shader definition registry
  plugin/ndrCycles/discovery.cpp
Labels: bug

#51 Support for FaceVarying and Uniform normals
  plugin/hdCycles/mesh.cpp
  plugin/hdCycles/mesh.h
  plugin/hdCycles/utils.cpp
Labels: bug, enhancement

#77 Enabling motion blur for geometries with varying topology
  plugin/hdCycles/camera.cpp
  plugin/hdCycles/camera.h
  plugin/hdCycles/mesh.cpp
  plugin/hdCycles/mesh.h
Labels: bug, enhancement

#82 Fixed merge typo
  plugin/hdCycles/camera.cpp
Labels: bug

#67 Mesh refactoring and adding Osd uniform subdivision
  .clang-format
  plugin/hdCycles/CMakeLists.txt
  plugin/hdCycles/mesh.cpp
  plugin/hdCycles/mesh.h
  plugin/hdCycles/meshRefiner.cpp
  plugin/hdCycles/meshRefiner.h
  plugin/hdCycles/renderParam.cpp
  plugin/hdCycles/renderParam.h
  plugin/hdCycles/utils.cpp
  plugin/hdCycles/utils.h
Labels: enhancement

#107 Uncomment the code to compute the deform blur steps
  plugin/hdCycles/mesh.cpp
Labels: bug

#110 Deferring adding curve to scene to when geometry is available
  plugin/hdCycles/basisCurves.cpp
Labels: bug

#117 Fix hdCycles crash on updating volumes PT-835
  plugin/hdCycles/openvdb_asset.h
  plugin/hdCycles/volume.cpp
  plugin/hdCycles/volume.h
Labels: bug
